### ISSUE TITLE
undefined is not an object (evaluation 'window.location.protocol')

### ISSUE THREAD

**Issue by xzf158** [adonisjs/adonis-websocket-client#45]
When I used this lib in Reactnative on Android, I'll get this error.  
This error is in Ws.browser.js line 1595,  in RN, it doesn't have window object. 
![wechatimg33](https://user-images.githubusercontent.com/702785/40954038-375d299e-68b5-11e8-9a93-6a667d4279ba.jpg)

**Comment by thetutlage** [comment]
Yup, `window` is required to create a websocket connection. I don't do react native much. Does react native has Browser compatible Websocket support?

**Comment by xzf158** [comment]
react native runtime is similar to nodejs. There is no `window` object but `global` variable.  Websocket is supported in RN. I removed this line of code, it worked.  But I find that `window` is being used at other places in this file such as  `window.localStorage`. It will cause error too.

**Comment by thetutlage** [comment]
The websocket-client is written for Browsers and not for Node.js. So it is expected that `window` references will be find at certain places. 

Most probably we need a react-native client. As I said, I don't do much of react native, I will need some time to read more about it and create a client.

If you want, you can fork this repo and make required changes to be react/vue native compliant. Also you will have to port the tests, so that they pass in React native not in browser

**Comment by xzf158** [comment]
Thank you  for your advice. I'll try to make it compatible with react-native.
